services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../backend:/var/www/backend
    environment:
      - COMPOSER_HOME=/composer
    networks:
      - app-network

  nginx:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www/backend:ro
      - ../frontend:/var/www/frontend:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  node:
    image: node:24
    working_dir: /var/www/frontend
    volumes:
      - ../frontend:/var/www/frontend
    command: ["tail", "-f", "/dev/null"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
